# Generated by Django 3.1.4 on 2020-12-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvyield',
            name='state',
            field=models.CharField(editable=False, max_length=2, primary_key=True, serialize=False),
        ),
    ]
