# Generated by Django 3.1.4 on 2020-12-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yields', '0002_auto_20201215_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvyield',
            name='state_full',
            field=models.CharField(default='NaN', editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
