# Generated by Django 3.1.4 on 2020-12-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yields', '0003_pvyield_state_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvyield',
            name='state_full',
            field=models.TextField(editable=False),
        ),
    ]
